import React from 'react';
import { Sparkles, HelpCircle } from 'lucide-react';
import { Skeleton } from '../common/Loader';

export default function InsightCard({
  insights = [],
  loading = false,
  onGenerate
}) {
  if (loading) {
    return (
      <div className="bg-white border border-gray-200 rounded p-6 space-y-4 font-sans">
        <div className="flex items-center gap-2">
          <Skeleton className="h-5 w-5 rounded-full" />
          <Skeleton className="h-4 w-32" />
        </div>
        <div className="space-y-2">
          <Skeleton className="h-3 w-full" />
          <Skeleton className="h-3 w-5/6" />
          <Skeleton className="h-3 w-4/5" />
        </div>
      </div>
    );
  }

  return (
    <div className="bg-white border border-gray-200 rounded-lg p-6 font-sans hover:border-gray-300 transition duration-150">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2 text-black">
          <Sparkles size={16} className="text-black" />
          <h3 className="text-sm font-bold tracking-tight">AI Business Insights</h3>
        </div>
        
        <div className="group relative">
          <HelpCircle size={13} className="text-gray-300 hover:text-gray-600 transition cursor-help" />
          <div className="absolute right-0 bottom-full mb-1.5 hidden group-hover:block w-48 bg-black text-white text-[10px] p-2 rounded shadow-md leading-relaxed z-10 font-normal">
            Insights are dynamically generated by Gemini based on your uploaded CSV data.
          </div>
        </div>
      </div>

      {insights && insights.length > 0 ? (
        <div className="space-y-4">
          {insights.map((insight, index) => (
            <div key={index} className="p-4 bg-gray-50/60 border border-gray-200 rounded-md text-xs">
              <div className="font-bold text-gray-900 mb-1">{insight.title}</div>
              <p className="text-gray-600 leading-relaxed">{insight.detail}</p>
            </div>
          ))}
        </div>
      ) : (
        <div className="border border-dashed border-gray-200 rounded-md p-8 text-center bg-gray-50/20">
          <p className="text-xs text-gray-400 leading-relaxed max-w-md mx-auto">
            No recommendations generated. Upload business sales or inventory data, then DashNova will analyze performance and recommend optimizations.
          </p>
          {onGenerate && (
            <button
              onClick={onGenerate}
              className="mt-4 h-8 px-4 border border-black hover:bg-black hover:text-white text-black text-xs font-bold rounded transition cursor-pointer"
            >
              Analyze & Generate Insights
            </button>
          )}
        </div>
      )}
    </div>
  );
}
